### ISSUE TITLE
Set up the Front end application

### ISSUE THREAD

**Issue by Layla-Hammoud** [Layla-Hammoud/E-Menue#1]
# Descrption
We should set up a React project, organize it, and create the basic components

# Tasks
- [x] Set up the React project
- [x] Architect the project structure
- [x] Create the navbar component
- [x] Create the footer component
